sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
before_install:
- git config user.name "opentracingci"
- git config user.email "opentracingci+opentracing@googlegroups.com"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials
install:
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script:
- travis/publish.sh
branches:
  except:
  - "/^[0-9]/"

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "MK0G3RJNvmP4f4kTCkaE3EhIj7AJHyiXowUb/Zh9O1pGiTzreTKS4OYM+KVWnP6twIDTfAaR6ZcXJBAFMexNTZ9yzz9QOQp99ue3TzVzIvQb+zlet0jUFMGbMxpBpL6nExq/gaJU1dJ5dmBp3OLxKkqhRqnSVPN1icv4X6z6RTL9Pc89tULRbAc6Eao4hJ2xv8Q/enfrqurXHTv/odgrHTknIU60he0GqNJU3KRqMP5c0mY7kKoGYSOM6TF4apcE5d7TQogbNqwq9gmQ4AzGQIVTnxh7UTtLtKzVzjIw1/y65o1aJBRWPxw6LX/SWOLRUd0FdAhwJsqzqs9lcu4kDoFLQqIXqq8HVT3TCcVubUx9bLj7sK/aWZ9fv2AuZmGmYglawxlHNC7sb60Af6c4HdvwYVYz+rKgHHQHOP8Y9p2A66xfQTxlYMb3feYfKfB1/h2F4tM/jJlMfU4LesEFTCwBX7R6Yb1DbS6MsPpF7N1hBVsf3L/CISrQBtAnILYu4mCt7qd8dd7MGdcXuDvDuR9nJ00z79xbq2lg5imqj96IGVs40iCCeJOKvDGr9CM99JFXrrWXbAS7GhsVAxnwFp0y6NRPper5m4WRVaFFjMSWN6RQKIB5WQZEFkEZJ29sulUx0SDAHI3WpmdxhiQBe0rj2HdsLmfuFhA1P+vMBn8="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "BlpBUnEg22p3t3ruHAqGptpcL/H4kKQwrYisL9utm3qeb2iqZ6ERaXJYCXslTmoWtRYohEsDak5Zy2kDlz3792PMp5QaWEiZgBb4um3fmiY8veDJdOT+/0DZFFly8QcLfNGfPNTYvf5pDGuJ7hvwKwJm5A8RGrvCA9Mjbp4/ebNN6gHQ4gi5WePKSs2Y97QLZAzxyAUooVE2WSV4NNrgVoZyNt1hviN5UExcS/HoXgjPWGmNFkz0umSgDlEjHoEgJcF4S0gTG31d46npIIihV8Oz6PL4G+GvGgPBhnOsHQYsy1dxxLFXvtkkigXp20szSEM/0rEszOolOSPy4RnuM0NQoCpESE2dQ3LBWB4Zm/q/Houv3LAgJcNHFoFLksyaYQHxT9naeUqNg4yiLmPfqDTMVO/MSGVyDPCxO0aRImMTvQITPifnNRpyP88UKSvpIdwrWArJC8QC4VwZ0IgjVzaHceD07Ix/o78aOyazUqPUVWHTzJT9Cezt62XoLwecXPfGYgLE3E40VXBvjLhrPbcJ1n8Z/WayhVcsqub1wDcICQ0gvCy6D/czbPxKUYmVJ6qIX7H/jqFZkn6fLToMH/X/XX8Nc3W9NQMY//QAuaiMjVSA9eORdxDAlej8GR7vRH1+USGyIySsJ9JVORsBDe7abWQdm82cCqeVpMvgipA="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "eCdxE0l4NhG4PAdHL45uZxRgQ+Y+rq3AqC3j9lYqrr9huq9PbS4VkiSQgJrHzS7Tvw2A44YP4DqDSLUAOWPyhDzcOQUR2zKXj+PtH0mSTfm2h2s/f90qKrG8CA6ze3bS5eY7kBaayihVFFkVPw3OBqZs9rjWpR+eN9yESzBU0MjGSsIUj0yZa2u37yIJsYyV60CYj+Pfm8nBx9BrsioSoN1co4/3u1PzyO2yuf5E05AirfNWYy5kgMrPHziQ57nO4oUN1RyIZpjP7J42ZIWVEOSgGiHBhCjv2WwTRYZ7EB2oCC81qF4uSVGuBGzMoXl+KUdpf0Z3vRBsPKFG1GiSU+e4C2RW5SQhuj5j1Le0Y6X1DhegcUl6zTgEE4X0ye2GEuZUfjTk8iGOls3sfNkWqLNpDTtziwGmJtpVtsDJ4QjtvUhYFGpTVu/Upk0vfiX995x0BA8IwEfa5uvX1UW7meKo+yWt/6BJQT5udSCoph4o6CMI2FgWis6X6tcfaQwcU2AR8CeLZeuvgte1IURLCj/p7bVfjR+eLCTnul8m086ofQvFoP994kRxcxCct6JUTi3z1UXsVFlhNQ6R0HaNxX3ADd5P8Qtx19BLQ9CEPal4duRhUDo3pqTSNtS5sy/e37zYZWis47kqKFV9p58oJXmpceMGcIj3lQVG+UaTpwY="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "IvapxUZuJ+PDXvf3KKe3tiJa8wsg3vftwzma193N+eKHk5csutslhszV2qEP8XlzkmXPP0vWMDMwguISSKfpHVsERR5BMOEgb+aszz9ppU/jUUgoqa+QxTHyw7l0bYrjxpd7iDSgiMFEfGbjKnXdio2Pu2pkV6zHZTDkrucVrhUdqNALTsMNTUtx/V2CpnS1OCDOJAjZp3FRx0BsyOZGA3ovvtuRaPdHvR2vHTHOReNoUCN+dKdFCJ2rOk0cGBMBXch9Aym9T9ZxdVZ8EV9O8rl1w3jWmoN28XUegpfHNwZ80oTMdHRaJnkA0yIQu3j4nyafH4exmMMN0lhg9n16SaIowtVKztAZOtyiBnEcYjSssB13l4grj5lYWpXiXy+rLQOcIc9BftN82qQ058ZHxTVOMbQ8dCSMW3MhGergml5gYYONER3wMFyjAQewq3/qBLB7uiRu8IjSJEzmV/426QSfBHjOEZArgC5jXk35czJxW8/AR27bv/BZv75gITRgNRgCCsIiTPpV1YZPmmu0/HOAq/0CxpQCUcZs1PHYQEdMJWFMIoPiZ4YB+XXiTxdAzHIB2jcTDZ+6bKE7otHgNj3BJALCBGcDZw9pKzBxWTIrSNnof2wo1m2JAxNJF3J/b61P9y+Bx7rgtA1FOKm0Z3ein8gAcKzp+ULjit+tUgM="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "mLVs3rkIHm0U8dpVlNzbkfgGT30IOzeBb2QPf0v76jmcB8VH5j375WWk5ePUAlSk+VcvPM1+pjYmhS3aZwp5/Z3zoXspR+MnkI+NKYdGpbnUDgt6RNtDbNWo4kqrXo0BTKLutEMoYWEbaksSXgH9sA7RgroXmE3fuBn5MNzjAIZWOr9q+K944MKcgi/+jgbHIwH9m+hIXdk98qTObCrLfie0Qza6iz/oEIEUC806XqaCGDaS2TiGC6Ti3l4IS45cxQSIXsRkuno4d6x4cHM7meHujOQ3mKJs/jH8ssxdrRX0Mb5YgJg82Fxe41iHcT9Xd3ZAt2r4SLYT+a5lc0CS3XKQ9yFnLb9Os+CpLM89jopvF1GKcJsvLeXX0zC3wMr/MD0LaQVCZKgtvgkEJ+YGydq0OCeMgmB2lvds6YW/vrCJ93fVXJngM0i4JwhVXWVQ6kGr7/FmqdbZeNV6aLBPFt/P5TQE+dhpQsRVPcuKGRsmGIJtz+TtSSsXceW6/AbFyALNHlTX+PQwdLBzKbjHWgFwdZEvKx3xsYbMIXmGugTOfY5Kad4A9MIndHCTOe4i4vuo0oTLpkavXjuXPfXd2Rzp43lL/z2/6X20BM4FAg2dJzXE5+5G6pRoH4pBTgx3/yU+I/wi9zAi3ECjYpmgG9U0nPCr6/DVzlGBdL4PnGQ="
